### ISSUE TITLE
What is the second argument to c-include?

### ISSUE THREAD

**Issue by patrickmay** [borodust/bodge-chipmunk#1]
The documentation isn't clear on why c-include needs a second argument.

**Comment by borodust** [comment]
Second argument is the name of the asdf system to resolve paths against.

Tbh, documentation of `:claw` is basically non-existent. It borrows a lot from `cl-autowrap`, but no claw-specific API is documented.

**Comment by borodust** [comment]
I do have plans on documenting it though, just need to finish adding C++ support.
